### PR TITLE
Update mesa.spec to build D3D12 and Zink drivers.

### LINKED ISSUE #2379: [Mesa enhancement request] Add Zink driver to mesa
Greetings ClearLinux team,
is there the possibility to add the ZINK driver to the mesa package?

Mesa library Zink docs URL: https://docs.mesa3d.org/drivers/zink.html
Extensive Zink infos URL: https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/

Additional remarks: There are a lot of movements in Zink development lately, mostly carried out by Mike Blumenkrantz. Most of the latest impressive improvements are still to be merged to Mesa master branch but starting to have ZINK added to the mesa package SPEC file will give us the possibility to benefit from them as soon as they are officially merged (which shouldn't be that far out).

Mike Blumenkrantz blog URL: https://www.supergoodcode.com/

Many thanks in advance :)

### LINKED ISSUE #2418: Mesa: Add D3D12 Gallium driver for use on Windows
This driver has been available since Mesa 21.0. Clear Linux has a version above this and has set auto for the Gallium drivers. However, per this comment: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3774#note_690117, D3D12 isn't included. So explicitly include it for VM and container images.

### PR DESCRIPTION
**Pull request by WSLUser**
Closes https://github.com/clearlinux/distribution/issues/2418 and 
Closes https://github.com/clearlinux/distribution/issues/2379

### CODE REVIEW

**Comment by WSLUser** [comment]
First time submitting a PR for a spec, if there's anything more I need to do, let me know.

**Comment by WSLUser** [comment]
@fenrus75 Can you help me know what else is needed? Do I need to update the spec versioning or anything?

**Comment by fenrus75** [comment]
so the spec file is autogenerated by autospec (our tooling for this) and it takes these inputs from the "configure" file.
I've done the equivalent change to the configure file and kicked off the automation.. if it comes out ok it'll be in the next build

**Comment by fenrus75** [comment]
it's.. not so easy. the suggested option does not work, everything after the auto is ignored.
fixing that suddenly needs a lot more packages added as build dep

**Comment by WSLUser** [comment]
Thanks for trying.  I hope it's something that can be resolved. Maybe you could throw a patch file in that detects the supported platforms for D3D12 and Zink. For example, if hyper-v is enabled and you can verify the kernel is running in hyper-v, you can then be sure that you can add the D3D12 driver. Also keep in mind the kernel needs to be built with `CONFIG_DXGKRNL=y`. As far as Zink goes, I did notice some issues floating around regarding Vulkan support not being quite where it should be. That could be part of the problem as Zink relies on Vulkan support.

**Comment by fenrus75** [comment]
I got the mesa side of it working eventually.
the kernel side I'm not yet clear about but .. one step at a time.

it was quite a bit more involved than this PR implies though

**Comment by WSLUser** [comment]
Yeah like I said it was my first time trying to contribute to a Clear Linux package so had no idea what else might of been needed. I sent a PR for the D3D12 for kernel already. That one is a simple one at least as it's just a config change. As far as Zink goes, I'm imagining it was the reason you had to pull more things in. Could you tell me what the other dependencies are? I'm looking to get Zink supported by another distro as well and don't want to hit the same wall twice.

**Comment by fenrus75** [comment]
the messy part was directx-headers

**Comment by WSLUser** [comment]
Ah yes. Those headers are only found on Windows so trying to build for native Linux would fail. I suppose a conditional statement could be added to check if it's being built on a Windows VM or not.  The headers themselves are open source so somebody could port them to Linux if they wanted.

**Pull request closed without merging**
